### ISSUE TITLE
実行できません

### ISSUE THREAD

**Issue by 7shi** [Tomatio13/mcp-server-tavily#1]
エラーで実行できませんでした。試した手順を書きます。環境は Windows 11 です。

`D:\llm` で git clone します。README に書かれている設定ではディレクトリの例が `"C:\\your_path\\tavily_search"` と書かれています。tavily_search というディレクトリが見当たらないため、リポジトリのディレクトリを指定しました → `"D:\\llm\\mcp-server-tavily"`

Claude アプリでエラーになったため、手動で uv を起動したときのエラーログは以下の通りです。

```
D:\llm\mcp-server-tavily>uv --directory D:\llm\mcp-server-tavily run tavily-search
  × Failed to build `tavily-search @ file:///D:/llm/mcp-server-tavily`
  ╰─▶ Build backend failed to build editable through `build_editable` (exit code: 1)                                    
      [stderr]
      Traceback (most recent call last):
        File "<string>", line 11, in <module>
          wheel_filename = backend.build_editable("C:\\Users\\7shi\\AppData\\Local\\uv\\cache\\builds-v0\\.tmpA1tJ81",
      {}, None)
        File "C:\Users\7shi\AppData\Local\uv\cache\builds-v0\.tmpL9VaZV\Lib\site-packages\hatchling\build.py", line
      83, in build_editable
          return os.path.basename(next(builder.build(directory=wheel_directory, versions=['editable'])))
                                  ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File
      "C:\Users\7shi\AppData\Local\uv\cache\builds-v0\.tmpL9VaZV\Lib\site-packages\hatchling\builders\plugin\interface.py",
      line 155, in build
          artifact = version_api[version](directory, **build_data)
        File "C:\Users\7shi\AppData\Local\uv\cache\builds-v0\.tmpL9VaZV\Lib\site-packages\hatchling\builders\wheel.py",
      line 496, in build_editable
          return self.build_editable_detection(directory, **build_data)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\7shi\AppData\Local\uv\cache\builds-v0\.tmpL9VaZV\Lib\site-packages\hatchling\builders\wheel.py",
      line 507, in build_editable_detection
          for included_file in self.recurse_selected_project_files():
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
        File
      "C:\Users\7shi\AppData\Local\uv\cache\builds-v0\.tmpL9VaZV\Lib\site-packages\hatchling\builders\plugin\interface.py",
      line 180, in recurse_selected_project_files
          if self.config.only_include:
             ^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\7shi\AppData\Roaming\uv\python\cpython-3.13.0-windows-x86_64-none\Lib\functools.py", line 1037,
      in __get__
          val = self.func(instance)
        File "C:\Users\7shi\AppData\Local\uv\cache\builds-v0\.tmpL9VaZV\Lib\site-packages\hatchling\builders\config.py",
      line 713, in only_include
          only_include = only_include_config.get('only-include', self.default_only_include()) or self.packages
                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~^^
        File "C:\Users\7shi\AppData\Local\uv\cache\builds-v0\.tmpL9VaZV\Lib\site-packages\hatchling\builders\wheel.py",
      line 262, in default_only_include
          return self.default_file_selection_options.only_include
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\7shi\AppData\Roaming\uv\python\cpython-3.13.0-windows-x86_64-none\Lib\functools.py", line 1037,
      in __get__
          val = self.func(instance)
        File "C:\Users\7shi\AppData\Local\uv\cache\builds-v0\.tmpL9VaZV\Lib\site-packages\hatchling\builders\wheel.py",
      line 250, in default_file_selection_options
          raise ValueError(message)
      ValueError: Unable to determine which files to ship inside the wheel using the following heuristics:
      https://hatch.pypa.io/latest/plugins/builder/wheel/#default-file-selection

      The most likely cause of this is that there is no directory that matches the name of your project
      (tavily_search).

      At least one file selection option must be defined in the `tool.hatch.build.targets.wheel` table, see:
      https://hatch.pypa.io/latest/config/build/

      As an example, if you intend to ship a directory named `foo` that resides within a `src` directory located at
      the root of your project, you can define the following:

      [tool.hatch.build.targets.wheel]
      packages = ["src/foo"]
```

**Comment by Tomatio13** [comment]
失礼しました。フォルダ構成を変更したことで起動できなくなっていました。
再度コミットしたのでご確認下さい。

**Comment by 7shi** [comment]
ありがとうございます。無事に起動しました。
